
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nicolas
 */
public class ordenamiento extends javax.swing.JFrame {

    /**
     * Creates new form ordenamiento
     */
    public ordenamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ordenar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buscarn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Numer = new javax.swing.JTextField();
        Ingresar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Matriz = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ordenar.setText("Ordenar");
        Ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenarActionPerformed(evt);
            }
        });

        Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Ingresada"},
                {null, "Ascendente"},
                {null, "Descendente"}
            },
            new String [] {
                "Posicion", "Lista"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Lista);

        jLabel4.setText("Ordenamiento numeros y busqueda :");

        jLabel3.setText("Numero a buscar:");

        buscarn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarnActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad de Números:");

        Numer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumerActionPerformed(evt);
            }
        });

        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });

        Matriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(Matriz);

        jButton2.setText("Regresar al Menú");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43)
                                .addComponent(Numer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(buscarn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(Ordenar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Numer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ingresar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ordenar)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenarActionPerformed
        if(Numer.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese una cantidad de Numeros");
        }
        else{
            int x =Integer.parseInt(Numer.getText());
            String [] Vector= new String [x];
            int [] VectorInt = new int [x];
            String [] VectorString= new String [x];
            int num=Matriz.getColumnCount();
            for(int i=0;i<num;i++)
            Vector[i]=(String)Matriz.getValueAt(0, i);
            for(int j=0;j<x;j++)
            VectorInt[j]=Integer.parseInt(Vector[j]);
            int menor;
            //ORDENAR
            for(int i = 0; i < num; i++){
                for (int j = i+1; j < num; j++) {
                    if(VectorInt[i]>VectorInt[j]){
                        int a=VectorInt[i];
                        VectorInt[i]=VectorInt[j];
                        VectorInt[j]=a;
                    }
                }
            }
            for (int i = 0; i < num; i++) {
                VectorString[i]= ""+VectorInt[i];
            }
            System.out.println(Arrays.toString(VectorInt));
            DefaultTableModel model= (DefaultTableModel)Matriz.getModel();
            model.addRow(VectorString);
            for(int i=0;i<num;i++){
                Vector[i]=(String)Matriz.getValueAt(0, i);
            }
            for(int i=0;i<num;i++){
                VectorInt[i]=Integer.parseInt(Vector[i]);
            }

            for(int i = 0; i < num; i++){
                for (int j = i+1; j < num; j++) {
                    if(VectorInt[i]<VectorInt[j]){
                        int aux=VectorInt[i];
                        VectorInt[i]=VectorInt[j];
                        VectorInt[j]=aux;
                    }
                }
            }

            for (int i = 0; i < num; i++) {
                VectorString[i]= ""+VectorInt[i];
            }
            System.out.println(Arrays.toString(VectorInt));
            model.addRow(VectorString);
            Ordenar.setEnabled(false);
        }

    }//GEN-LAST:event_OrdenarActionPerformed

    private void buscarnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarnActionPerformed

    private void NumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumerActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        // TODO add your handling code here:
        if(Numer.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese una cantidad de Numeros");
        }
        else{
            int n = Integer.parseInt(Numer.getText());
            int[][] matriz = new int[3][n];
            tableMatriz(matriz, n);
            Ingresar.setEnabled(false);
        }
    }//GEN-LAST:event_IngresarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu men= new Menu();
        men.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(buscarn.getText().equals(""))
        JOptionPane.showMessageDialog(null,"Ingrese una cantidad de Numeros");
        else{
            int x =Integer.parseInt(Numer.getText());
            int num=Matriz.getColumnCount();
            int num2=Matriz.getRowCount();
            String [] Vector= new String [x];
            int [] VectorInt = new int [x];
            int cont=0;
            String [] VectorString= new String [x];
            int nume =Integer.parseInt(buscarn.getText());

            for(int i=0;i<num;i++){
                Vector[i]=(String)Matriz.getValueAt(0, i);
            }
            for(int j=0;j<x;j++){
                VectorInt[j]=Integer.parseInt(Vector[j]);
                if (VectorInt[j]==nume)
                {

                    Lista.setValueAt(j+1, 0, 0);
                    cont++;
                }
            }
            //
            for(int i=0;i<num;i++){
                Vector[i]=(String)Matriz.getValueAt(1, i);
            }
            for(int j=0;j<x;j++){
                VectorInt[j]=Integer.parseInt(Vector[j]);
                if (VectorInt[j]==nume)
                {

                    Lista.setValueAt(j+1, 1, 0);
                    cont++;
                }
            }
            //
            for(int i=0;i<num;i++){
                Vector[i]=(String)Matriz.getValueAt(2, i);
            }
            for(int j=0;j<x;j++){
                VectorInt[j]=Integer.parseInt(Vector[j]);
                if (VectorInt[j]==nume)
                {

                    Lista.setValueAt(j+1, 2, 0);
                    cont++;
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

   private void tableMatriz(int[][] matriz, int n) {
        DefaultTableModel model = (DefaultTableModel) Matriz.getModel();
        model.setColumnCount(n);//cidad de Columnas    }
        model.setRowCount(1);

}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ordenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ordenamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JTable Lista;
    private javax.swing.JTable Matriz;
    private javax.swing.JTextField Numer;
    private javax.swing.JButton Ordenar;
    private javax.swing.JTextField buscarn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
